model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
dataset = "justus27/math-hendrycks-genesys-format"
batch_size = 32
dp = 6
rollout_path = "outputs"
output_path = "data_rollout"
max_model_len = 16000
async_level = 1
calibration_n = 8

[sampling]
n = 16
