model_name = "Qwen/Qwen3-4B"
dataset = "justus27/rl-math-filtered-difficult"
batch_size = 11
dp = 6
rollout_path = "outputs"
output_path = "data_rollout"
max_model_len = 10000
async_level = 1
calibration_n = 10

[sampling]
n = 8
temperature = 0.7
