model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
project = "rl-calibration-experiments"

max_async_level = 1

[train]
micro_bs = 1 # change to 8 for H200
reshard_after_forward = true

[optim]
batch_size = 128
warmup_steps = 1
total_steps = 100000000000000
step_per_rollout = 4

[optim.optim]
lr = 1e-6



[data]
path = "data_rollout"
seq_length = 16000

[ckpt]
rollout_path = "outputs"

